# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- bash: |
    which bash
    echo Hello $name
    echo about to ls -al
    ls -al
    echo about to ls -al pipelines
    ls -al pipelines
    echo about to check the python version
    echo about to get the versions of python
    python ––version
    python3 ––version
    python3.7 ––version
    sudo apt update
    sudo apt install software-properties-common
    echo skipping deadsnakes because it requires user input
    sudo apt update
    sudo apt install python3.7
    python ––version
    python3 ––version
    python3.7 ––version
  displayName: Multiline Bash script
  env:
    name: Microsoft