# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- bash: |
    which bash
    echo Hello $name
    echo about to ls -al
    ls -al
    echo about to ls -al pipelines
    ls -al pipelines
    echo about to get the versions of python
    sudo find / -type f -executable -iname 'python*' -exec file -i '{}' \; | awk -F: '/x-executable; charset=binary/ {print $1}' | xargs readlink -f | sort -u | xargs -I % sh -c 'echo -n "%: "; % -V'
    echo about to test timeit
    python3 -m timeit -h # for details
    echo about to try to run terraform deployment script
    python3 deploy-network.py
  displayName: Multiline Bash script
  env:
    name: Microsoft