## Copyright 2020 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/GreenRiverIT    

#Very simple playbook just to test connection.  
- name: Simple playbook example 
  hosts: demoservers
  remote_user: agile-cloud

  tasks:  

     - name: Get user name
       shell: whoami
