## Copyright 2020 Green River IT (GreenRiverIT.com) as described in LICENSE.txt distributed with this project on GitHub.  
## Start at https://github.com/GreenRiverIT    

#Get the Dev Server provisioned for Jekyll.  
- name: Provision Apache Server 
  hosts: demoservers
  remote_user: agile-cloud
  vars:
    extra_path: /home/agile-cloud/bin
  vars_files:
    - myVars.yaml
  vars_prompt: 
    - name: "git_password" 
      prompt: "Password for 'https://{{ git_org_user }}@dev.azure.com'"
      private: yes 

  tasks:  

    - name: Get user name
      shell: whoami

    - name: Run whoami command as root
      shell: whoami
      become: true
      become_user: root
      vars:
        ansible_become_password: "{{ rt_pass }}"

    - name : Update all yum packages
      yum: 
        name: '*'
        state: latest 
        update_cache: true
        lock_timeout: 180
      become: true
      become_user: root
      vars:
        ansible_become_password: "{{ rt_pass }}"

    - name: Install httpd
      yum:
        name: httpd
        state: latest
      become: true
      become_method: sudo
      become_user: root
      vars:
        ansible_become_password: "{{ rt_pass }}"

    - name: Create /home/agile-cloud/artifact/ directory
      file:
        path: /home/agile-cloud/artifact/
        state: directory

    - name: Clone static site artifact  
      git:
        repo: https://{{ git_org_user | urlencode }}:{{ git_password | urlencode }}@dev.azure.com/{{ git_org_user }}/{{ project_name }}/_git/{{ repo_name }}
        dest: /home/agile-cloud/artifact/
        

    - name: Remove .gitignore file (delete file)
      file:
        path: /home/agile-cloud/artifact/.gitignore
        state: absent

    - name: Recursively remove ,git directory
      file:
        path: /home/agile-cloud/artifact/.git
        state: absent

    - name: Recursively change ownership of a directory
      file:
        path: /var/www/html/
        state: directory
        recurse: yes
        owner: agile-cloud
        group: agile-cloud
      become: true
      become_user: root
      vars:
        ansible_become_password: "{{ rt_pass }}"

#    - name: Move directory contents
#      command: cp -r /home/agile-cloud/artifact/. /var/www/html/

    - name: Ansible copy files remote to remote
      shell: 'cp -r /home/agile-cloud/artifact/. /var/www/html/'

#    - name: Copy index.html with owner and permissions
#      copy:
#        src: config-files/index.html
#        dest: /var/www/html/index.html
#        owner: agile-cloud
#        group: agile-cloud
#        mode: '0775'
#      become: true
#      become_method: sudo
#      become_user: root
#      vars:
#        ansible_become_password: "{{ rt_pass }}"

    #Reload systemctl after installing httpd
    - name: force systemd to reread configs
      systemd:
        daemon_reload: yes
      become: true
      become_method: sudo
      become_user: root
      vars:
        ansible_become_password: "{{ rt_pass }}"

    - name: Make sure a service is running
      systemd:
        state: started
        name: httpd
      become: true
      become_method: sudo
      become_user: root
      vars:
        ansible_become_password: "{{ rt_pass }}"

    - name: Enable service httpd and ensure it is not masked
      systemd:
        name: httpd
        enabled: yes
        masked: no
      become: true
      become_method: sudo
      become_user: root
      vars:
        ansible_become_password: "{{ rt_pass }}"

